version: "3.8"

services:
  spring:
    container_name: spring-container
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      - database
      - session
      - cache

  session:
    image: redis:6.2.4-alpine
    container_name: session-container
    env_file: .env
    ports:
      - "6379:6379"
    command:
      - --requirepass ${REDIS_SESSION_PASSWORD}

  cache:
    image: redis:6.2.4-alpine
    container_name: cache-container
    env_file: .env
    ports:
      - "6380:6379"
    command:
      - --requirepass ${REDIS_CACHE_PASSWORD}