# 개발

logging:
  level:
    root: debug

spring:
  output:
    ansi:
      enabled: always

  redis:
    token:
      host: ENC(XgFskmj0RIDPuqO/dBsuR14BlPixi9gH)
      port: ENC(UCyEkGwkMsBgr3tsjA0jbQ==)
      password: ENC(0NYDSvTobBO2yan5bcd3P5zmdUQ2EEL2)

  datasource:
    url: jdbc:h2:mem:devlog;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa

  devtools:
    add-properties: false

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: ENC(lCWkXu2730IXSJEYd98+r1dFtu0hnodh)
    port: ENC(ucLR9dFcbyUTT8S8V5eWcw==)
    username: ENC(TMLzCuf3oeMERcFoQnUBRepEAeap7EK0)
    password: ENC(9NFkMGtb4LUswKKnPQl27OZp/8MYc299wjiEwcK0xgk=)
  properties:
    mail:
      smtp:
        auth: true
        starttls:
          enable: true
  h2:
    console:
      enabled: true
      path: /h2-console