# 운영

logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: ${MARIADB_URL}
    username: ${MARIADB_USERNAME}
    password: ${MARIADB_PASSWORD}

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
         format_sql: true