# 공통

spring:
  profiles:
    active: dev

  output:
    ansi:
      enabled: always

  devtools:
    add-properties: false

  jpa:
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
