# 공통

server:
  error:
    include-message: always

spring:
  profiles:
    active: dev

  output:
    ansi:
      enabled: always

  devtools:
    add-properties: false

  jpa:
    open-in-view: false