# 개발

logging:
  level:
    root: debug

spring:
  datasource:
    url: jdbc:h2:mem:devlog
    driver-class-name: org.h2.Driver
    username: sa

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true