# 개발

logging:
  level:
    root: debug

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/devlog
    username: test
    password: password

  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  cache:
    type: redis

  redis:
    session:
      host: localhost
      port: 6379
      password: session-password

    cache:
      host: localhost
      port: 6380
      password: cache-password
