# 개발

logging:
  level:
    root: debug

spring:
  output:
    ansi:
      enabled: always

  cache:
    type: redis

  redis:
    session:
      host: ENC(LIr0A1A0XlK4TIDJjBNYBYHn3e5ThgOn)
      port: ENC(zhpvCtCt8vAZc1Xxc/QOnQ==)
      password: ENC(7xYc5CnMZAwpPPQgY97rkZ4OrtGJzJzN)

    cache:
      host: ENC(9ZczRWLSjlKV5PE/8nqvjeahUveB1qFj)
      port: ENC(rWoLJ96FB7e3kHgp+SbNTg==)
      password: ENC(YFSpn9ISnl5NGI3JSBhBzg3KsfGqBCYc)

  datasource:
    url: jdbc:h2:mem:devlog
    driver-class-name: org.h2.Driver
    username: sa

  devtools:
    add-properties: false

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(TMLzCuf3oeMERcFoQnUBRepEAeap7EK0)
    password: ENC(9NFkMGtb4LUswKKnPQl27OZp/8MYc299wjiEwcK0xgk=)
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

  h2:
    console:
      enabled: true
      path: /h2-console