# 개발

logging:
  level:
    root: debug

spring:
  output:
    ansi:
      enabled: always

  cache:
    type: redis

  redis:
    cache:
      host: ENC(wOE0C4t/QQZ1xQ2C+78CREq5wDLhNASC)
      port: ENC(WA37eyHWagVJsRJUuQyo5A==)
      password: ENC(M5a8/CUZrpchoR+uz9pj2BTPzvMHu7ZU)

    session:
      host: ENC(XfGxkVFSaG7hBakUenpnQedw8x2NABC0)
      port: ENC(gL/w90O1H/m/NQ4nei8FPw==)
      password: ENC(BlWoa+bOuRhpHMb5Sz1xLmiaaJ0fasvC)

  datasource:
    url: jdbc:h2:mem:devlog;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa

  devtools:
    add-properties: false

  jpa:
    database: h2
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(TMLzCuf3oeMERcFoQnUBRepEAeap7EK0)
    password: ENC(9NFkMGtb4LUswKKnPQl27OZp/8MYc299wjiEwcK0xgk=)
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

  h2:
    console:
      enabled: true
      path: /h2-console