# 운영

logging:
  level:
    root: info

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    database: mysql

  cache:
    type: redis

  redis:
    session:
      host: session-container
      port: ${REDIS_SESSION_PORT}
      password: ${REDIS_SESSION_PASSWORD}

    cache:
      host: cache-container
      port: ${REDIS_CACHE_PORT}
      password: ${REDIS_CACHE_PASSWORD}